version: '3.9'
services:
  yp-fe:
    container_name: yp-fe
    hostname: yp-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8055:80"

networks:
  default:
    external: true
    name: yp-network
